DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    original_url TEXT NOT NULL,
    clicks INTEGER NOT NULL DEFAULT 0,
    daily INTEGER NOT NULL DEFAULT 0,
    weekly INTEGER NOT NULL DEFAULT 0,
    monthly INTEGER NOT NULL DEFAULT 0,
    last_use TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
